### PR TITLE
Jest: limit maxWorkers, maxConcurrency and use workerThreads

### PR DESCRIPTION
**Pull request by XhmikosR**
The time difference hit isn't that big. We might even want to go with `os.cpus() - 4` or `os.cpus() / 2`.

Now Jest doesn't spawn 600 processes on my Windows VM.

CI seems to be slower, though. We could use a different number of threads for CI.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Did you try the branch? If it's not significantly slower, I'd like to keep it simple.

I don't see the point of spawning 600+ processes when running the tests, regardless of the OS.

**Comment by Kreeg** [comment]
No I didn't. If it OK on your machine and CI - I'm OK with that.

**Review by Kreeg — APPROVED** [review]

**Comment by XhmikosR** [comment]
Could you give it a go on your machine too? I'd like to see how big is the slowdown there before we merge this.

CI is the same, because it has 2 threads which is the minimum we set.

**Comment by Kreeg** [comment]
@XhmikosR 34.548 s vs 30.104 s (config vs main). So it is OK.

**Pull request merged**
