### PR TITLE
Add support for disabling root viewBox attribute in stack mode

### PR DESCRIPTION
**Pull request by Arkkimaagi**
This is the PR to fix: https://github.com/svg-sprite/svg-sprite/issues/303

With it you can disable viewBox attribute rendering in the root element. By default the attribute is rendered with `true`, but when you set `false`, it's not added.

### CODE REVIEW

**Comment by Kreeg** [comment]
Hello @Arkkimaagi! Thank you for this PR. I have few thoughts about it.

1. Maybe the config attribute name should be named with camelCase. And since it is boolean, it should have more boolean-specific name, like `setRootViewBox` or somewhat like that
2. This branch of code at least should have been tested with integration tests of stack mode (we currently haven't covered modes by unit tests yet). My suggestion is to add `rootviewbox` config in stack test configuration of SVGSprite

@XhmikosR what do you think?

**Comment by Arkkimaagi** [comment]
I actually had it at first in camel case, but since I did not see other configs in camel case, I converted it to this. I wanted to match the convention. I'm okay with any change tho. Just let me know.

**Comment by XhmikosR** [comment]
I'd say better be consistent with the existent options for now, although I agree they are not optimal.

**Comment by Arkkimaagi** [comment]
I'm going to need help with the tests. 🤔

**Comment by Kreeg** [comment]
@XhmikosR are you saying about options naming or about adding new option?

**Comment by XhmikosR** [comment]
@Kreeg Both; @Arkkimaagi is consistent with the options pattern we follow here.

**Comment by Arkkimaagi** [comment]
Thanks @Kreeg, I hope I cherry-picked it properly :D

**Comment by Arkkimaagi** [comment]
Hmm, I seriously hope I got these things done correctly. If this is getting messy, you can just use my code on a new branch or what ever. I'd just love to see this feature in svg-sprite, I do not care who gets the "credit" of writing it. :)

**Comment by Kreeg** [comment]
@Arkkimaagi sorry but it went worse. I created a new pr #666. Closing this now

**Pull request closed without merging**
