### PR TITLE
Backport the `lodash.trim` and `lodash.trimStart` removal to 2.x

### LINKED ISSUE #840: [v2.0.2] - Can we upgrade v2.0.2 to have lodash version that fixes the lodash.trim vulnerability
Hi all.

I would like to introduce a change to bump up the 2.0.2 release of svg-sprite to fix the following vulnerability https://github.com/advisories/GHSA-29mw-wpgm-hmr9

Here is a screenshot of the vulnerability after NPM audit:

Screen Shot 2023-08-25 at 2 04 02 pm

My fix will involve replacing the individual lodash packages with 4.,17.21 version of the entire lodash package. It's currently on my own fork here:
https://github.com/classicmike/svg-sprite/commit/f31c8003297b313aa3d2db29cc1cbb8f6be86f3c

Questions on this if we were to go ahead with this fix, where can I redirect my PR to? I'm asking this because it seems like this repo is working towards a version 3 which already has breaking changes. My assumption would be is to create a new branch on this repo based on the v2.0.2 tag then I PR to that new branch and publish a new v2.0.3 release from there.

Anybody managing this project could you please let me know. Thanks.

### PR DESCRIPTION
**Pull request by martell2010**
Fixes #840

### CODE REVIEW

**Review by Luen — APPROVED** [review]

**Comment by martell2010** [comment]
@Luen Hi, this fix is for version 2.0.2, while 3.0.0 is still beta, can we make a branch for ver.2 and merge this one there?

**Review by lemkaa — APPROVED** [review]

**Comment by valentin9** [comment]
any update on this? It would be super nice to have it merged or backport the changes from 3 to here.
@XhmikosR

**Comment by aivLuk** [comment]
@martell2010 hi, can conflicts be solved and these changes merged?

**Comment by martell2010** [comment]
@aivLuk we can't merge it into main branch due to version 3 being there.

**Comment by XhmikosR** [comment]
This isn't needed on main.

**Comment by XhmikosR** [comment]
If you meant to target the

**Comment by XhmikosR** [comment]
If you meant to target the 1.5.x branch please make a new PR and make sure you target the right branch and CI is green.

**Comment by XhmikosR** [comment]
Unfortunately, I don't think the patch is complete. There are more changes in main, like default params, which I don't think we can backport.

**Comment by XhmikosR** [comment]
I'm not 100% this is 1-to-1 change, that's why I haven't merged it yet... I guess I'd have to take a decision and go ahead with this and a patch version. In case we introduce a breaking change, I suppose we can roll back the changes.

**Review by XhmikosR — APPROVED** [review]

**Pull request merged**
