### PR TITLE
lib/svg-sprite.js: revert change from e85b53c

### LINKED ISSUE #740: bug: 2.0.0: `shape.id.separator` does not produce an `id` with the parent directory names
In 1.5.0 `shape.id.separator` traversed full directory path + file name into the shape ID. Now in 2.0.0 shape ID is always a svg file name, without any parent folders.

### PR DESCRIPTION
**Pull request by XhmikosR**
It should really fix #740 

I'll try to release a new 2.0.2 version after this is merged.

EDIT: BTW this doesn't seem to be covered by the tests, any help adding a test case is welcome :)

### CODE REVIEW

**Comment by XhmikosR** [comment]
Note that we could probably revert #745 and go with the old code. Unsure if https://github.com/svg-sprite/svg-sprite/commit/e85b53c6343dd78d1a5eccae137e2b337be94a5a has caused more issues, so it might make more sense to revert it altogether.

**Comment by XhmikosR** [comment]
Wouldn't it be better if we reverted both? See my comment above.

**Comment by XhmikosR** [comment]
I mean, I'm not sure if we are missing something in tests and that patch has caused even more damage. I did it in a hurry and it might have caused more issues.

**Comment by Kreeg** [comment]
This line is not covered yet by the unit tests. And all the snapshots are done with absolute svg paths. I'm not sure how to deal with this. We can just double up all the regression tests with the relative svgs

**Comment by XhmikosR** [comment]
All I'm saying is that maybe it's safer for now if we just revert things to what it was and we can see if we can revisit this later. Since the old code did work.

**Comment by Kreeg** [comment]
@XhmikosR do you want to revert both https://github.com/svg-sprite/svg-sprite/pull/745 and https://github.com/svg-sprite/svg-sprite/commit/e85b53c6343dd78d1a5eccae137e2b337be94a5a ?

**Comment by XhmikosR** [comment]
Yeah, minus the tests from #745 if they still pass.

**Comment by Kreeg** [comment]
Yes, let's do this

**Comment by XhmikosR** [comment]
OK, so I tried it but there are issues in shape.js. Unsure how to proceed...

**Comment by Kreeg** [comment]
I'll fix this tomorrow

**Comment by Kreeg** [comment]
@XhmikosR please take a look. Previously all "files" in those test were fake mocks. Now they're real Vinyl files. I think this is correct

**Comment by XhmikosR** [comment]
@Kreeg thanks! Does this mean that now tests will catch such regression in the future?

Is the PR ready from your side?

**Comment by XhmikosR** [comment]
@Kreeg friendly ping :) Is this ready from your side? If so I'll merge it and cut a 2.0.2 later.

The next release should be a v3.0.0 assuming we manage to update svgo to 3.x and csso to 5.x :)

**Comment by Kreeg** [comment]
@XhmikosR yes, I think it's ready

**Pull request merged**
