### PR TITLE
shape.js: simplify ENTITY regex

### PR DESCRIPTION
**Pull request by XhmikosR**
Split from #436.

@jkphl XML is case sensitive, isn't it? If so, the regex shouldn't use the `i` flag, right?

### CODE REVIEW

**Review by jkphl — APPROVED** [review]

**Comment by XhmikosR** [comment]
@jkphl shouldn't we remove the ignore case flag?

**Comment by jkphl** [comment]
@XhmikosR We could probably do this, yet. But it's not particularly harmful either, right?

**Comment by XhmikosR** [comment]
Not harmful, but IIRC it's not valid XML so we shouldn't care about it?

**Comment by jkphl** [comment]
I'm fine with its removal. Just wanted to drop that I usually try to stick to [Postel's Law](https://en.wikipedia.org/wiki/Robustness_principle):

> Be conservative in what you do, be liberal in what you accept from others

😉

**Comment by XhmikosR** [comment]
While I agree to some extent, I don't think we shouldn't rely on the specs. :)

I'll drop the ignore flag here too.

**Pull request merged**
