### PR TITLE
Replace `_.clone` with Object spread

### PR DESCRIPTION
**Pull request by XhmikosR**
Unsure about the second change (`...element._nsMap`). The first one should be fine since `defaultSVGConfig` is an object.

### CODE REVIEW

**Review by Kreeg — APPROVED** [review]

**Comment by XhmikosR** [comment]
@Kreeg did you check the second instance so that we are safe? :)

**Comment by Kreeg** [comment]
It'll be an empty object. By the way, there is no `_nsMap` in `Element` declaration. Maybe it was in earliest versions of `xmldom`?

**Comment by XhmikosR** [comment]
Hmm, not sure at all. The codebase wasn't touched until last year I started updating some stuff. We can remove it in a separate PR if you think it's redundant.

**Comment by Kreeg** [comment]
OK

**Pull request merged**
