### PR TITLE
Replace `_.invoke` with vanilla JS

### PR DESCRIPTION
**Pull request by XhmikosR**
@jkphl this seems to work, but I haven't checked if lodash did exactly the same.

Refs #604

### CODE REVIEW

**Comment by Kreeg** [comment]
In original code addressed line of code just do not do anything. Shapes is an array, which has not `resetNamespace` method. So the lodash method here just quietly fails.
I've added test case. You can check yourself that method is not called.
The only way to run it is to call `_.invoke(shapes, '0.resetNamespace')`
Maybe that has worked differently in older versions of lodash.

**Comment by XhmikosR** [comment]
Yeah, I also noticed it was undefined hence why I tried with forEach. Unsure how to proceed though...

**Comment by Kreeg** [comment]
I think we should comment out this whole block and add todo to return to this later.

**Comment by Kreeg** [comment]
@XhmikosR OK, I checked this. I compared the svg's gotten from `npm run example` and `npm run test` commands between `main` and this branches. They are the same.
The real intentions was to call `resetNamespace` on each shape, because shapes are just an array and this method exists only in `SVGShape`. So I assume it is safe. Unit tests here is useless because the previous code did nothing. There is nothing to test except the regression tests, which are OK.

**Comment by XhmikosR** [comment]
@Kreeg thanks! I'm not sure if it's OK TBH, but we could land this and see how it goes.

**Pull request merged**
